"""
Django settings for SkillTrek project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path

# Load environment variables from .env file
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'False'

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',  # Required for dj-rest-auth
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

THIRD_PARTY_APPS = [
    'rest_framework',  # Provides powerful tools for building Web APIs
    'rest_framework.authtoken',  # Handles token-based authentication for the REST API

    'corsheaders',
    # Manages Cross-Origin Resource Sharing (CORS), allowing the server to handle requests from different origins

    'dj_rest_auth',  # Offers REST API endpoints for user authentication and registration
]

INSTALLED_APPS += THIRD_PARTY_APPS

MY_APPS = [
    'user_management.apps.UserManagementConfig',
    'courses.apps.CoursesConfig',
    'landing_page.apps.LandingPageConfig',
]

INSTALLED_APPS += MY_APPS

SITE_ID = 1  # Required for dj-rest-auth

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SkillTrek.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

WSGI_APPLICATION = 'SkillTrek.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_management.CustomUser'

# Custom settings.py for Django REST framework settings
REST_FRAMEWORK = {
    # Default Date and Time format for serialized data output
    'DATETIME_FORMAT': "%d-%b-%Y, %a %I:%M %p",  # Format: Day-Month-Year, Weekday Hour:Minute AM/PM
    'DATE_FORMAT': '%d-%b-%Y',  # Format: Day-Month-Year for date fields

    # Default authentication classes to be used in the REST API
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Token-based authentication for stateless clients
        # 'rest_framework.authentication.SessionAuthentication',  # Use session-based authentication for browser clients
    ],
    # Default permission classes that determine who has access to the API views
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authenticated users by default for all views
    ],
}

# DJRESTAUTH_TOKEN_MODEL = None  # Disable token authentication model for dj-rest-auth

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Allow requests from your Next.js frontend
    # Add your production domain here as well if needed
]

# If you want to allow credentials (cookies, session):
CORS_ALLOW_CREDENTIALS = True

# Optionally allow specific headers if needed
CORS_ALLOW_HEADERS = [
    'Authorization',  # Required for token authentication
    'Content-Type',  # Needed for sending JSON or form data
    'X-CSRFToken',  # Required for CSRF protection
]

# Email settings for sending emails using Django
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


FRONTEND_URL = "http://localhost:3000"

PASSWORD_RESET_TIMEOUT = 1800  # Token valid for 30 minutes (in seconds)

REST_AUTH_SERIALIZERS = {
    'PASSWORD_RESET_SERIALIZER': 'user_management.password_reset_serializers.CustomPasswordResetSerializer',
}
